name: Build
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
        cmake: [2.6, 2.8, 3.0, 3.3]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: ${{ matrix.cmake }}

      - name: Verify cmake version
        run: cmake --version

      - name: Build with ${{ matrix.compiler }}
        run: |
          mkdir build
          cd build

          if [[ "${{ matrix.compiler }}" == "gcc" ]]; then
            export CC=gcc
            export CXX=g++
          else
            export CC=clang
            export CXX=clang++
          fi

          cmake .. -DCMAKE_BUILD_TYPE=Release

          # verify in CMakeCache.txt that the compiler is set to the correct one
          grep -q $COMPILER CMakeCache.txt || exit 1

          make -j $(nproc)
